name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install talloc
      run: sudo apt-get install -y libtalloc-dev
    - name: Install glfw3
      run: sudo apt-get install -y glfw3
    - name: Install check
      run: sudo apt-get install -y check
    - name: make
      run: make
      env:
        CC: clang
    - name: make check
      run: make check

  mac:
    runs-on: macos-11

    steps:
      - name: install dependancies
        run: brew install talloc glfw3 check
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: make
        run: make
      - name: make check
        run: make check
