name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependances
      run: sudo apt-get install -y libtalloc-dev libglfw3-dev check
    - name: Install Vulkan
      run: sudo apt-get install -y libvulkan-dev vulkan-validationlayers-dev
    - name: configure
      run: configure
    - name: make
      run: make
      env:
        CC: clang
    - name: make check
      run: make check

  mac:
    runs-on: macos-11

    steps:
      - name: install dependancies
        run: brew install talloc glfw3 check vulkan-headers
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure
        run: configure
      - name: make
        run: make
      - name: make check
        run: make check
