name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB: true
  SHADERCC: ./tools/fake-shadercc.sh

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Linux Dependencies
      if: startsWith(matrix.os, "ubuntu")
      run: >
        sudo apt-get update &&
        sudo apt-get install -y libtalloc-dev libglfw3-dev check &&
        sudo apt-get install -y libvulkan-dev vulkan-validationlayers-dev
    - name: Mac Dependencies
      if: startsWith(matrix.os, "macos")
      run: brew install talloc glfw3 check vulkan-headers molten-vk
    - name: Make directories
      run: mkdir build
    - name: configure
      run: (cd build && cmake ..)
    - name: make
      run: (cd build && make)
      env:
        CC: clang
        VULKANLIBS: -lMoltenVK
    - name: Tests
      run: ./build/trtl_check
