name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: nashidau/turtle-support
        path: third-party/turtle-support
    - name: Install Dependances
      run: sudo apt-get install -y libtalloc-dev libglfw3-dev check
    - name: Install Vulkan
      run: sudo apt-get install -y libvulkan-dev vulkan-validationlayers-dev
    - name: configure
      run: ./configure
    - name: make
      run: make -k
      env:
        CC: clang
        GITHUB: true
        SHADERCC: ./third-party/turtle-support/linux/glslc
    - name: make check
      run: make check

  mac:
    runs-on: macos-11

    steps:
      - name: install dependancies
        run: brew install talloc glfw3 check vulkan-headers molten-vk
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: nashidau/turtle-support
          path: third-party/turtle-support
      - name: configure
        run: ./configure
      - name: make
        run: make
        env:
          GITHUB: true
          SHADERCC: ./third-party/turtle-support/mac/glslc
      - name: make test
        run: make trtl_check
      - name: Run tests
        run: ./trtl_check
