name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    compiler: clang  

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install talloc
      run: sudo apt-get install -y talloc
    - name: Install glfw3
      run: sudo apt-get install -y glfw3
    - name: Install check
      run: sudo apt-get install -y check
    - name: make
      run: make
    - name: make check
      run: make check
